version: '3.8'

services:
  cometbft:
    image: cometbft/cometbft:v0.38.0
    container_name: cometbft-node
    ports:
      - "26656:26656"  # P2P port
      - "26657:26657"  # RPC port
    environment:
      - CMTHOME=/cometbft
    volumes:
      - ./testnet/node0:/cometbft
    command: ["node", "--proxy_app=tcp://gridway:26658"]
    depends_on:
      gridway:
        condition: service_healthy
    networks:
      - gridway-network
    restart: unless-stopped

  gridway:
    image: ${GRIDWAY_IMAGE:-gridway:test}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gridway-app
    ports:
      - "26658:26658"  # ABCI port
      - "9090:9090"    # gRPC port
      - "1317:1317"    # REST API port (Cosmos SDK standard)
    environment:
      - RUST_LOG=info
      - GRIDWAY_CHAIN_ID=${CHAIN_ID:-gridway-testnet}
      - GRIDWAY_HOME=/gridway
    volumes:
      - ./testnet/gridway:/gridway
    networks:
      - gridway-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "26658"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

networks:
  gridway-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  cometbft-data:
  gridway-data: