[package]
name = "gridway-errors"
version = "0.1.0"
edition = "2021"
authors = ["mconcat"]
license = "AGPL-3.0"
repository = "https://github.com/mconcat/gridway"
description = "Error handling types and utilities for the gridway blockchain framework"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
