//! Node configuration for gridway validators.
//!
//! Follows Alto's Config pattern for YAML-based configuration.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::net::SocketAddr;

/// Configuration for a gridway validator node.
#[derive(Deserialize, Serialize)]
pub struct NodeConfig {
    /// Hex-encoded Ed25519 private key for node identity.
    pub private_key: String,
    /// Hex-encoded BLS12-381 threshold share for consensus signing.
    pub share: String,
    /// Hex-encoded BLS12-381 threshold polynomial for the validator set.
    pub polynomial: String,

    /// P2P listening port.
    pub port: u16,
    /// Prometheus metrics port.
    pub metrics_port: u16,
    /// HTTP API port for transaction submission and balance queries.
    /// Set to 0 to disable.
    #[serde(default)]
    pub tx_port: u16,
    /// Directory for persistent storage (consensus state, archives).
    pub directory: String,
    /// Number of tokio worker threads.
    pub worker_threads: usize,
    /// Log level (trace, debug, info, warn, error).
    pub log_level: String,

    /// Whether to use local networking mode (loopback addresses).
    pub local: bool,
    /// Hex-encoded Ed25519 public keys of allowed peers.
    pub allowed_peers: Vec<String>,
    /// Hex-encoded Ed25519 public keys of bootstrapper nodes.
    pub bootstrappers: Vec<String>,

    /// Maximum number of pending messages per p2p channel.
    pub message_backlog: usize,
    /// Size of internal mailboxes for actor communication.
    pub mailbox_size: usize,
    /// Size of deque buffers for broadcast engine.
    pub deque_size: usize,

    /// Number of threads for parallel signature verification.
    pub signature_threads: usize,

    /// Optional bearer token for authenticating sensitive API endpoints
    /// (e.g. /snapshot). If unset, those endpoints are unrestricted.
    #[serde(default)]
    pub api_token: Option<String>,

    /// Optional path to an encrypted keystore directory.
    /// If set, the node will attempt to load its private key from the
    /// keystore instead of using the plaintext `private_key` field.
    #[serde(default)]
    pub keystore_path: Option<String>,

    /// Name of the key in the keystore to load (default: "node").
    #[serde(default = "default_keystore_key_name")]
    pub keystore_key_name: String,
}

fn default_keystore_key_name() -> String {
    "node".to_string()
}

/// A list of peers provided when a validator is run locally.
#[derive(Deserialize, Serialize)]
pub struct Peers {
    pub addresses: HashMap<String, SocketAddr>,
}


/// Genesis state configuration.
///
/// Defines the initial chain state loaded into BaseApp on first start.
/// Generated by `gridway-setup` and stored as `genesis.yaml`.
#[derive(Deserialize, Serialize, Clone, Debug)]
pub struct GenesisConfig {
    /// Chain identifier (e.g. "gridway-1").
    pub chain_id: String,
    /// Initial accounts with balances.
    pub accounts: Vec<GenesisAccount>,
}

/// A genesis account with initial balances.
#[derive(Deserialize, Serialize, Clone, Debug)]
pub struct GenesisAccount {
    /// Hex-encoded address (20 bytes / 40 hex chars).
    pub address: String,
    /// Hex-encoded Ed25519 public key.
    pub public_key_hex: String,
    /// Initial token balances.
    pub balances: Vec<GenesisBalance>,
}

/// A single denomination balance for a genesis account.
#[derive(Deserialize, Serialize, Clone, Debug)]
pub struct GenesisBalance {
    /// Token denomination (e.g. "ugridway").
    pub denom: String,
    /// Initial amount.
    pub amount: u64,
}
