name: ABCI Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  abci-integration:
    name: ABCI Integration Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y librocksdb-dev protobuf-compiler libssl-dev pkg-config
    
    - name: Install Tendermint
      run: |
        # Install Tendermint for ABCI testing
        TENDERMINT_VERSION="0.34.29"
        wget https://github.com/tendermint/tendermint/releases/download/v${TENDERMINT_VERSION}/tendermint_${TENDERMINT_VERSION}_linux_amd64.tar.gz
        tar -xzf tendermint_${TENDERMINT_VERSION}_linux_amd64.tar.gz
        sudo mv tendermint /usr/local/bin/
        tendermint version
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-
    
    - name: Build Helium
      run: cargo build --release
    
    - name: Initialize Tendermint
      run: |
        tendermint init
        # Configure Tendermint for ABCI app
        sed -i 's/proxy_app = "tcp:\/\/127.0.0.1:26658"/proxy_app = "tcp:\/\/127.0.0.1:26658"/' $HOME/.tendermint/config/config.toml
    
    - name: Start Helium ABCI Server
      run: |
        # Start the Helium ABCI server in the background
        cargo run --release --bin helium-server -- --abci-port 26658 &
        HELIUM_PID=$!
        echo "HELIUM_PID=$HELIUM_PID" >> $GITHUB_ENV
        sleep 5  # Wait for server to start
    
    - name: Start Tendermint
      run: |
        # Start Tendermint node
        tendermint node --proxy_app=tcp://127.0.0.1:26658 > tendermint.log 2>&1 &
        TENDERMINT_PID=$!
        echo "TENDERMINT_PID=$TENDERMINT_PID" >> $GITHUB_ENV
        sleep 10  # Wait for Tendermint to start
    
    - name: Test ABCI Connection
      run: |
        # Test that Tendermint can connect to the ABCI app
        curl -s http://localhost:26657/status | jq .
    
    - name: Run ABCI Integration Tests
      run: |
        # Run specific ABCI integration tests if they exist
        cargo test --release --features integration-tests abci_integration || echo "No ABCI integration tests found"
    
    - name: Check Logs on Failure
      if: failure()
      run: |
        echo "=== Tendermint Logs ==="
        cat tendermint.log || true
        echo "=== Helium Server Logs ==="
        # Add any Helium server logs if available
    
    - name: Cleanup
      if: always()
      run: |
        # Kill processes
        kill $HELIUM_PID || true
        kill $TENDERMINT_PID || true