name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  claude-review:
    # Only run when @claude is mentioned in a comment or PR description
    if: |
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request && 
       contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request' && 
       contains(github.event.pull_request.body, '@claude'))
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          # model: "claude-opus-4-20250514"
          
          # No direct_prompt - Claude will only respond to @claude mentions
          # This ensures the workflow runs but Claude only reviews when explicitly asked
          
          # Optional: Add specific tools for running tests or linting
          # allowed_tools: "Bash(cargo test),Bash(cargo clippy),Bash(cargo fmt --check)"