name: Format and Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt-lint:
    name: Format and Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y librocksdb-dev protobuf-compiler libssl-dev pkg-config
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-
    
    - name: Install cargo-component
      run: |
        cargo install cargo-component --locked
    
    - name: Add wasm32-wasip1 target
      run: rustup target add wasm32-wasip1
    
    - name: Build WASI modules (generates bindings)
      run: ./scripts/build-wasi-modules.sh
    
    - name: Check formatting
      run: |
        # Get all workspace members and check formatting, skipping WASI modules
        WASI_MODULES=("ante-handler" "begin-blocker" "end-blocker" "tx-decoder")
        
        # Get all package names from workspace
        PACKAGES=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.source == null) | .name')
        
        for pkg in $PACKAGES; do
          # Skip if it's a WASI module
          if [[ " ${WASI_MODULES[@]} " =~ " ${pkg} " ]]; then
            echo "Skipping formatting check for WASI module: $pkg"
            # Check only the lib.rs file for WASI modules
            if [ -f "crates/wasi-modules/$pkg/src/lib.rs" ]; then
              rustfmt --check "crates/wasi-modules/$pkg/src/lib.rs"
            fi
          else
            echo "Checking formatting for: $pkg"
            cargo fmt -p $pkg -- --check
          fi
        done
    
    - name: Run clippy
      run: cargo clippy --workspace --exclude ante-handler --exclude begin-blocker --exclude end-blocker --exclude tx-decoder -- -D warnings