name: WASM Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  wasm-test:
    name: Test WASM Modules
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-wasip1
    
    - name: Install wasmtime
      run: |
        curl https://wasmtime.dev/install.sh -sSf | bash
        echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-registry-wasm-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-wasm-
    
    - name: Build WASM modules
      run: |
        # Build each WASM module separately
        for module in crates/wasi-modules/*/; do
          if [ -f "$module/Cargo.toml" ]; then
            echo "Building $module"
            cd "$module"
            cargo build --release --target wasm32-wasip1
            cd - > /dev/null
          fi
        done
    
    - name: Test WASM module loading
      run: |
        # Test that WASM modules can be loaded
        for module in crates/wasi-modules/*/; do
          if [ -d "$module/target/wasm32-wasip1/release" ]; then
            for wasm in "$module"/target/wasm32-wasip1/release/*.wasm; do
              if [ -f "$wasm" ]; then
                echo "Testing WASM module: $wasm"
                wasmtime compile "$wasm"
              fi
            done
          fi
        done
    
    - name: Validate WASM modules
      run: |
        # Validate WASM module structure
        for module in crates/wasi-modules/*/; do
          if [ -d "$module/target/wasm32-wasip1/release" ]; then
            for wasm in "$module"/target/wasm32-wasip1/release/*.wasm; do
              if [ -f "$wasm" ]; then
                echo "Validating WASM module: $wasm"
                wasmtime wasm2wat "$wasm" > /dev/null
              fi
            done
          fi
        done
    
    - name: Check WASM module sizes
      run: |
        # Report WASM module sizes
        echo "WASM Module Sizes:"
        for module in crates/wasi-modules/*/; do
          if [ -d "$module/target/wasm32-wasip1/release" ]; then
            ls -lh "$module"/target/wasm32-wasip1/release/*.wasm 2>/dev/null || true
          fi
        done
    
    - name: Run WASM-specific tests
      run: |
        # Run any WASM-specific tests if they exist
        for module in crates/wasi-modules/*/; do
          if [ -f "$module/Cargo.toml" ]; then
            echo "Running tests for $module"
            cd "$module"
            cargo test --target wasm32-wasip1 || echo "No WASM-specific tests found for $module"
            cd - > /dev/null
          fi
        done